apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Demo project for the prod environment
  sourceRepos:
  - '*'

  destinations:
  - namespace: 'prod'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'