apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Demo project for the dev environment
  sourceRepos:
  - '*'

  destinations:
  - namespace: 'dev'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'