apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-service-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: demo-project-dev
  source:
    path: demo-service/overlays/dev
    repoURL: https://github.com/yarelm/argocd-meetup-demo
    targetRevision: HEAD
